steps:
  # Step to check out the code from GitHub
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://$_GITHUB_TOKEN@github.com/Antony-2504/Node.js-Application-Code.git']
    dir: '/workspace'

  # Step to create the /workspace/secrets directory
  - name: 'bash'
    args:
      - '-c'
      - 'mkdir -p /workspace/secrets'

  # Step to copy the JSON key from Cloud Storage to /workspace/secrets/tera_sec.json
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://tera02/tera.json', '/workspace/secrets/tera_sec.json']

  # Step to initialize Terraform
  - name: 'hashicorp/terraform:latest'
    args: ['init']
    dir: '/workspace'

  # Step to validate Terraform configuration
  - name: 'hashicorp/terraform:latest'
    args: ['validate']
    dir: '/workspace'

  # Step to plan Terraform changes
  - name: 'hashicorp/terraform:latest'
    args: ['plan']
    dir: '/workspace'

  # Step to apply Terraform changes
  - name: 'hashicorp/terraform:latest'
    args: ['destroy', '-auto-approve']
    dir: '/workspace'
