steps:
  # Copy the Dockerfile to the instance
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'Dockerfile', 'antonyavanexa@instance-latest:/home/antonyavanexa/']

  # SSH into the instance and build the Docker image
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'ssh', 'antonyavanexa@instance-latest', '--zone=us-central1-a', '--command', 'sudo docker build -t baseimage:v1 /home/antonyavanexa/']

  # Confirm the Docker image creation
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'ssh', 'antonyavanexa@instance-latest', '--zone=us-central1-a', '--command', 'sudo docker images']
