steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$antony-2504/my-node-app', '.']

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$antony-2504/my-node-app']

  # Deploy the application on Google Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-node-app'
      - '--image=gcr.io/$antony-2504/my-node-app'
      - '--platform=managed'
      - '--region=us-central1'
