steps:
  # Step to check out the code from GitHub
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://$_GITHUB_TOKEN@github.com/Antony-2504/Node.js-Application-Code.git']
    dir: '/workspace'

  # Step to initialize Terraform
  - name: 'hashicorp/terraform:latest'
    args: ['init']
    dir: '/workspace'
    secretManager:
      secrets:
        - versionName: projects/880914408187/secrets/terra_sec/versions/1
          env: 'TF_VAR_credentials'

  # Step to validate Terraform configuration
  - name: 'hashicorp/terraform:latest'
    args: ['validate']
    dir: '/workspace'

  # Step to plan Terraform changes
  - name: 'hashicorp/terraform:latest'
    args: ['plan']
    dir: '/workspace'
