steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo $SA_KEY > /tmp/sa_key.json
    gcloud auth activate-service-account --key-file=/tmp/sa_key.json
    git clone https://github.com/Antony-2504/Node.js-Application-Code.git
    cd your-repo
    terraform init
    terraform plan
    terraform apply -auto-approve
