steps:
  # Step to check out the code from GitHub
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://$_GITHUB_TOKEN@github.com/Antony-2504/Node.js-Application-Code.git']
    dir: '/workspace'

  # Step to initialize Terraform
  - name: 'hashicorp/terraform:latest'
    args: ['init']
    dir: '/workspace'

  # Step to validate Terraform configuration
  - name: 'hashicorp/terraform:latest'
    args: ['validate']
    dir: '/workspace'

  # Step to plan Terraform changes
  - name: 'hashicorp/terraform:latest'
    args: ['plan']
    dir: '/workspace'

  # Step to apply Terraform changes
  - name: 'hashicorp/terraform:latest'
    args: ['apply', '-auto-approve']
    dir: '/workspace'
