steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/my-node-app', '.']

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/my-node-app']

  # Deploy the application to Google Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-node-app'
      - '--image=gcr.io/${PROJECT_ID}/my-node-app'
      - '--platform=managed'
      - '--region=us-central1'

images:
- 'gcr.io/${PROJECT_ID}/my-node-app'
