steps:
  # SSH into the instance
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'ssh', 'antonyavanexa@instance-demo', '--zone=us-central1-a', '--command', 'sudo touch /tmp/test']

  # Confirm directory creation
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'ssh', 'antonyavanexa@instance-demo', '--zone=us-central1-a', '--command', 'ls -l /tmp']
