steps:
  # Copy files to instance
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'scp', '--zone=us-central1-a', '--recurse', 'Dockerfile', 'test.sh', 'antonyavanexa@instance-latest:/var/test']

  # SSH into the instance and execute test.sh
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh antonyavanexa@instance-latest --zone=us-central1-a --command 'cd /var/test && chmod +x test.sh && ./test.sh'
