steps:
  # Step to initialize Terraform
  - name: 'gcr.io/cloud-builders/terraform'
    args: ['init']
    dir: 'terraform.tf'

  # Step to apply Terraform changes
  - name: 'gcr.io/cloud-builders/terraform'
    args: ['apply', '-auto-approve']
    dir: 'terraform.tf'
