steps:
  # Step to check out the code from GitHub
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://$_GITHUB_TOKEN@github.com/Antony-2504/Node.js-Application-Code.git']
    dir: '/workspace'

  # Step to initialize Terraform
  - name: 'hashicorp/terraform:latest'
    args: ['init']
    dir: '/workspace'

  # Step to provide credentials to Terraform
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['kms', 'decrypt', '--ciphertext-file=/secrets/terra_sec.enc', '--plaintext-file=/secrets/terra_sec.json', '--project=880914408187', '--location=global', '--keyring=my-keyring', '--key=my-key']
  - name: 'hashicorp/terraform:latest'
    args: ['init', '-backend-config=path.module=/secrets/terra_sec.json', '-input=false']
    dir: '/workspace'

  # Step to validate Terraform configuration
  - name: 'hashicorp/terraform:latest'
    args: ['validate']
    dir: '/workspace'

  # Step to plan Terraform changes
  - name: 'hashicorp/terraform:latest'
    args: ['plan', '-input=false']
    dir: '/workspace'

secrets:
  - kmsKeyName: projects/880914408187/locations/global/keyRings/my-keyring/cryptoKeys/my-key
    secretName: projects/880914408187/secrets/terra_sec
