steps:
  # Step 1: Install Terraform
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'run'
      - '--rm'
      - '-v'
      - '.:/workspace'
      - 'hashicorp/terraform:latest'
      - 'init'

  # Step 2: Terraform Plan
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'run'
      - '--rm'
      - '-v'
      - '.:/workspace'
      - 'hashicorp/terraform:latest'
      - 'plan'

  # Step 3: Terraform Apply
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'run'
      - '--rm'
      - '-v'
      - '.:/workspace'
      - 'hashicorp/terraform:latest'
      - 'apply'
      - '-auto-approve'
