steps:
  # Step to check out the code from GitHub
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://$_GITHUB_TOKEN@github.com/Antony-2504/Node.js-Application-Code.git']
    dir: '/workspace'

  # Step to initialize Terraform
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "export TF_VAR_credentials=\$$_TERA_JSON" >> /workspace/env.sh
        terraform init
    env:
      - '_TERA_JSON=$_TERA_JSON'

  # Step to validate Terraform configuration
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/env.sh
        terraform validate
    dir: '/workspace'

  # Step to plan Terraform changes
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/env.sh
        terraform plan
    dir: '/workspace'

  # Step to apply Terraform changes
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/env.sh
        terraform apply -auto-approve
    dir: '/workspace'
